name: dev
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: dev debug
    steps:
      - name: custom action
        id: dev_step
        uses: jon-bell/list-workflow-runs-by-branch-action@main
        with:
          # include_branches: 'main, dev'
          include_branches: 'fast-collision-free-coverage,reporting-ci'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          workflow_id: 'eval-24h-5x.yml'
          repo: jon-bell/JQF
      - name: print result
        run: echo ${{ steps.dev_step.outputs.workflow_runs }} 