name: dev
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: dev debug
    steps:
      - name: custom action
        id: dev_step
        uses: jon-bell/list-workflow-runs-by-branch-action@main
        with:
          include_branches: 'main, dev'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Use the output from the `hello` step
      - name: Get the output value
        run: echo "The output was ${{ steps.dev_step.outputs.workflow_runs }}"
